// /* eslint-disable */
// // @ts-nocheck
// // Generated by unplugin-vue-components
// // Read more: https://github.com/vuejs/core/pull/3399
// export {}

// /* prettier-ignore */
// declare module 'vue' {
//   export interface GlobalComponents {
//     PrimeContextMenu: typeof import('primevue/contextmenu')['default']
//     PrimeToast: typeof import('primevue/toast')['default']
//     RouterLink: typeof import('vue-router')['RouterLink']
//     RouterView: typeof import('vue-router')['RouterView']
//   }
// }
